#!/bin/bash -e

. $(dirname $0)/env_setup.sh

${LCG_release_area}/ccache/${CCACHE_VERSION}/${BINARY_TAG}/bin/ccache -z -F 2000

echo 'set(CMAKE_USE_CCACHE ON CACHE BOOL "")' >> cache_preload.cmake

/usr/bin/time -v bash -x -e -c "
  make BUILDDIR=${BUILDDIR} configure
  make BUILDDIR=${BUILDDIR} BUILDFLAGS=-j4 GaudiKernel
  make BUILDDIR=${BUILDDIR}
"

${LCG_release_area}/ccache/${CCACHE_VERSION}/${BINARY_TAG}/bin/ccache -s
