#!/bin/bash -e
#####################################################################################
# (c) Copyright 1998-2020 CERN for the benefit of the LHCb and ATLAS collaborations #
#                                                                                   #
# This software is distributed under the terms of the Apache version 2 licence,     #
# copied verbatim in the file "LICENSE".                                            #
#                                                                                   #
# In applying this licence, CERN does not waive the privileges and immunities       #
# granted to it by virtue of its status as an Intergovernmental Organization        #
# or submit itself to any jurisdiction.                                             #
#####################################################################################

. $(dirname $0)/env_setup.sh

${LCG_release_area}/ccache/${CCACHE_VERSION}/${BINARY_TAG/+py3/}/bin/ccache -z -F 2000

echo 'set(CMAKE_USE_CCACHE ON CACHE BOOL "")' >> cache_preload.cmake

/usr/bin/time -v bash -x -e -c "
  make BUILDDIR=${BUILDDIR} configure
  make BUILDDIR=${BUILDDIR} BUILDFLAGS=-j4 GaudiKernel
  make BUILDDIR=${BUILDDIR}
"

${LCG_release_area}/ccache/${CCACHE_VERSION}/${BINARY_TAG/+py3/}/bin/ccache -s
