#!/bin/bash -e

. $(dirname $0)/env_setup.sh

if [ -n "${CI}" ] ; then
  url="${CI_PROJECT_URL}/-/jobs/artifacts/${CI_COMMIT_REF_NAME}/download?job=${CI_JOB_NAME}"
  echo "downloading '${url}'"
  curl -o artifacts.zip --location "${url}"
  unzip -q artifacts.zip '.ccache/*' || true
fi

${LCG_release_area}/ccache/${CCACHE_VERSION}/${BINARY_TAG}/bin/ccache -z

echo 'set(CMAKE_USE_CCACHE ON CACHE BOOL "")' >> cache_preload.cmake
echo 'set(clang_format_cmd "'$(which lcg-clang-format-${CLANG_FORMAT_VERSION})'" CACHE FILEPATH "")' >> cache_preload.cmake

/usr/bin/time -v bash -x -e -c "
  make BUILDDIR=${BUILDDIR} configure
  make BUILDDIR=${BUILDDIR} BUILDFLAGS=-j4 GaudiKernel
  make BUILDDIR=${BUILDDIR}
"

${LCG_release_area}/ccache/${CCACHE_VERSION}/${BINARY_TAG}/bin/ccache -s
