# Default settings
# set(GAUDI_USE_AIDA             ON  CACHE BOOL "")
# set(GAUDI_USE_XERCESC          ON  CACHE BOOL "")
# set(GAUDI_USE_CLHEP            ON  CACHE BOOL "")
# set(GAUDI_USE_HEPPDT           ON  CACHE BOOL "")
# set(GAUDI_USE_CPPUNIT          ON  CACHE BOOL "")
# set(GAUDI_USE_UNWIND           ON  CACHE BOOL "")
# set(GAUDI_USE_GPERFTOOLS       ON  CACHE BOOL "")
# set(GAUDI_USE_DOXYGEN          ON  CACHE BOOL "")
# set(GAUDI_USE_INTELAMPLIFIER   OFF CACHE BOOL "")
# set(GAUDI_USE_JEMALLOC         ON  CACHE BOOL "")
# set(BUILD_TESTING              ON  CACHE BOOL "")
