# Disable everyting
set(GAUDI_USE_AIDA             OFF CACHE BOOL "")
set(GAUDI_USE_XERCESC          OFF CACHE BOOL "")
set(GAUDI_USE_CLHEP            OFF CACHE BOOL "")
set(GAUDI_USE_HEPPDT           OFF CACHE BOOL "")
set(GAUDI_USE_DOXYGEN          OFF CACHE BOOL "")
set(GAUDI_BUILD_EXAMPLES       OFF CACHE BOOL "")
set(GAUDI_ENABLE_GAUDIPARTPROP OFF CACHE BOOL "")
set(BUILD_TESTING              OFF CACHE BOOL "")
