#!/bin/bash -e

. $(dirname $0)/env_setup.sh

# make sure we do not re-run cmake
find ${BUILDDIR} -type f -exec touch -d $(date +@%s) \{} \;

mkdir -p ${BUILDDIR}/html
( make BUILDDIR=${BUILDDIR} test ARGS='-j4' || touch ${BUILDDIR}/html/tests_failed ) | tee ${BUILDDIR}/ctest.log
mv ${BUILDDIR}/html ${TESTS_REPORT}
mv ${BUILDDIR}/ctest.log ${TESTS_REPORT}
mv ${BUILDDIR}/Testing ${TESTS_REPORT}
if [ -e ${TESTS_REPORT}/tests_failed ] ; then
  # this prints all lines starting with a white space after and including "The following tests...", excluding lines with "Not Run"
  echo "================================================================================"
  awk '/^[^[:space:]]/{do_print=0}; /The following tests FAILED:/{do_print=1}; do_print&&!/Not Run/{print}' ${TESTS_REPORT}/ctest.log
  echo "================================================================================"
  exit 1
fi
