#!/bin/bash -e

. $(dirname $0)/env_setup.sh

${LCG_release_area}/ccache/${CCACHE_VERSION}/${BINARY_TAG}/bin/ccache -z -F 2000

# make sure we do not re-run cmake
find ${BUILDDIR} -type f -exec touch -d $(date +@%s) \{} \;

${LCG_release_area}/ccache/${CCACHE_VERSION}/${BINARY_TAG}/bin/ccache -z -M 1G
/usr/bin/time -v make BUILDDIR=${BUILDDIR} test_public_headers_build
${LCG_release_area}/ccache/${CCACHE_VERSION}/${BINARY_TAG}/bin/ccache -s
