#!/usr/bin/env python3
#####################################################################################
# (c) Copyright 1998-2026 CERN for the benefit of the LHCb and ATLAS collaborations #
#                                                                                   #
# This software is distributed under the terms of the Apache version 2 licence,     #
# copied verbatim in the file "LICENSE".                                            #
#                                                                                   #
# In applying this licence, CERN does not waive the privileges and immunities       #
# granted to it by virtue of its status as an Intergovernmental Organization        #
# or submit itself to any jurisdiction.                                             #
#####################################################################################

import os
import shelve
import sys
from optparse import OptionParser
from pathlib import Path

# https://gitlab.cern.ch/gaudi/Gaudi/-/issues/368
# Fixed in https://github.com/python/cpython/commit/8f2280272d7e551047b7fb3f7baea885275247b1 (3.13)
# and https://github.com/python/cpython/commit/8ab7081015e6b7233762fea23452d50569fc20b5 (3.14)
if (
    (3, 13, 0) <= sys.version_info <= (3, 13, 7) or sys.version_info[:3] == (3, 14, 0)
) and sys.platform.startswith("linux"):
    import dbm
    import dbm.gnu

    dbm._defaultmod = dbm.gnu

from GaudiKernel.DataHandle import DataHandle, DataHandleVector  # noqa: F401
from GaudiKernel.GaudiHandles import *  # noqa: F401 F403

parser = OptionParser(
    description="Script to merge confdb2_part files.",
    usage="%prog [options] input1 input2 ... [output|--output output]",
)
parser.add_option(
    "--ignore-missing",
    action="store_true",
    help="do not fail if an input file is missing, just ignore it",
)
parser.add_option(
    "--ignore-duplicates",
    action="store_true",
    help="do not fail if there are duplicate configurables in the inputs",
)
parser.add_option(
    "-i",
    "--inputs-file",
    help="text file with input file names if not given as arguments (one per line)",
)
parser.add_option(
    "-o", "--output", help="output filename (by default use the last argument)"
)

if __name__ == "__main__":
    opts, args = parser.parse_args()
    if not opts.inputs_file and len(args) < 1:
        parser.print_usage()
        sys.exit(0)

    import logging

    logging.basicConfig(format="merge_confdb2_parts: %(levelname)s %(message)s")

    output = Path(opts.output or args.pop())
    inputs = args
    if opts.inputs_file:
        inputs += Path(opts.inputs_file).read_text().splitlines()

    missing = [i for i in inputs if not os.path.isfile(i)]

    if missing:
        if opts.ignore_missing:
            inputs = [i for i in inputs if i not in missing]
            for i in missing:
                logging.warning("file %s not found", i)
        else:
            for i in missing:
                logging.error("file %s not found", i)
            sys.exit(1)

    def cleanup():
        """Helper to cleanup existing output files"""
        for path in output.parent.glob(f"{output.name}*"):
            path.unlink()

    try:
        # create the destination directory if missing
        if not output.parent.is_dir():
            os.makedirs(output.parent)
        logging.debug("opening %r for writing", output.as_posix())
        # shelve.open(filename) may create any of the following files:
        # - "{filename}"
        # - "{filename}.db"
        # - "{filename}.dat" and "{filename}.dir"
        # - or others in the future
        # but the lookup in GaudiConfig2 always uses "{filename}"
        # So we remove all existing files to avoid confusion
        cleanup()

        with shelve.open(output.as_posix(), "c") as out:
            for f in inputs:
                logging.debug("adding %r", f)
                input_conf = eval(open(f, "rb").read())
                duplicates = input_conf.keys() & out.keys()
                if duplicates:
                    for dup in duplicates:
                        logging.log(
                            (
                                logging.WARNING
                                if opts.ignore_duplicates
                                else logging.ERROR
                            ),
                            f"Duplicate configurable '{dup}' found in {f} ({input_conf[dup]['__declaration_location__']}). "
                            f"Already declared by another library in {out[dup]['__declaration_location__']}.",
                        )
                    if not opts.ignore_duplicates:
                        cleanup()
                        sys.exit(1)

                # merge the DBs
                out.update(input_conf)

        # then we make sure the output file exists (even if empty)
        output.touch()
    except Exception:
        cleanup()
        raise
